name: Build WF

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Maven build
        run: mvn install

  testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Maven test
        run: maven test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle